# Generated by Django 3.2.3 on 2021-10-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120, unique=True)),
                ('password', models.CharField(max_length=8, unique=True)),
                ('profile_image', models.ImageField(default='User_Image/no_profile_image.jpg', unique=True, upload_to='')),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
