# Generated by Django 3.2.3 on 2021-10-21 18:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0002_auto_20211021_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='code',
            name='commit_code',
            field=models.UUIDField(blank=True, default=uuid.UUID('21d0540a-4da0-46d8-bc89-07273bdfa573')),
        ),
    ]
